### ISSUE TITLE
Newtonsoft is not used

### ISSUE THREAD

**Issue by steveoh** [Harmonickey/Serilog.Sinks.SendGridEmail#1]
**Describe the bug**

You include newtonsoft json in the project but it is never used.

**Comment by Harmonickey** [comment]
True!  I have removed it and bumped the version to 2.0.1 should be available sometime today after it's finished uploading to nuget.

**Comment by steveoh** [comment]
I've vendored this project for now to update other dependencies and adding nullability. I can commit that all back but our formatting is all different and everything is different now.

**Comment by Harmonickey** [comment]
What formatting?  You mean the tab size is different?

**Comment by Harmonickey** [comment]
Also, if you have changes, feel free to just fork it and/or create a pull request, that way others can benefit from your changes.

**Comment by steveoh** [comment]
> What formatting? You mean the tab size is different?

Well you don't have an editorconfig or omnisharp.json so yeah, tabs converted to spaces, curlies went all over.

**Comment by Harmonickey** [comment]
Feel free to add one and make a pull request, I don't really mind.
